version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/pgsql/data
    volumes:
      - postgres:/var/lib/pgsql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres:
  pgadmin: